services:
  # --- Baza Danych (Punkt 5.2: Trwałość danych) ---
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StrongPassword123!
    ports:
      - "1433:1433"
    volumes:
      - my_db_data:/var/opt/mssql # To zapewnia, że dane nie znikną po restarcie
    restart: always

  # --- Backend API (Punkt 5.1: Obsługa DTO) ---
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_api
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=TaskDb;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=True
    depends_on:
      - db
    restart: on-failure

  # --- Frontend React (Punkt 5.4: Interfejs Użytkownika) ---
  frontend:
    image: node:22-alpine
    container_name: frontend_react_final
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3000"
    command: sh -c "npm install && npm run dev -- --host --port 3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8081/api
    stdin_open: true
    tty: true
    depends_on:
      - api

# Definicja wolumenu dla bazy danych (Punkt 5.2)
volumes:
  my_db_data: