name: Azure_Deploy_Final_Try

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build and Publish
        # Budujemy i publikujemy backend do folderu o nazwie 'gotowe'
        run: dotnet publish backend/Backend.csproj -c Release -o ./gotowe

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'api-task-juliawr'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          # Wysyłamy dokładnie to, co wygenerował Publish
          package: ./gotowe
