name: Strategy_B_Clean_Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build and Publish
        # Używamy -w (working directory), żeby GitHub wiedział, gdzie jest projekt
        run: dotnet publish backend/Backend.csproj -c Release -o ./publish_output

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-task-juliawr'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          # Wysyłamy TYLKO zawartość folderu publish_output
          package: ./publish_output
